### ISSUE TITLE
Empty 'DataFrame' error

### ISSUE THREAD

**Issue by balaramadurai** [amoghpj/org-report-summary-graphics#1]
Hi Amogh,
  I stumbled upon your blog post about org-clock report. http://amoghpj.github.io/org-report-graphics/

This is a fantastic idea. Now, I tried this out, but I get this error. Can you please help me with this?

```
Export done.
Export done.
Starting python script...
Reading tags...
Empty DataFrame
Columns: []
Index: [Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday]
Plotting...
Traceback (most recent call last):
  File "/home/bala/orgmode/Reviews/generate-org-report.py", line 98, in <module>
    FT.plot.bar(rot='45',ax=ax1)
  File "/usr/local/lib/python3.6/dist-packages/pandas/plotting/_core.py", line 3090, in bar
    return self(kind='bar', x=x, y=y, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/pandas/plotting/_core.py", line 2941, in __call__
    sort_columns=sort_columns, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/pandas/plotting/_core.py", line 1977, in plot_frame
    **kwds)
  File "/usr/local/lib/python3.6/dist-packages/pandas/plotting/_core.py", line 1804, in _plot
    plot_obj.generate()
  File "/usr/local/lib/python3.6/dist-packages/pandas/plotting/_core.py", line 258, in generate
    self._compute_plot_data()
  File "/usr/local/lib/python3.6/dist-packages/pandas/plotting/_core.py", line 373, in _compute_plot_data
    'plot'.format(numeric_data.__class__.__name__))
TypeError: Empty 'DataFrame': no numeric data to plot
```

The sample csv is given below:
```
File,Headline,Time,,,
,ALL *Total time*,*180:01*,,,
todo.org,*File time*,*180:01*,,,
,*1 Projects*,*31:20*,,,
,\_  /Publish the paper as a.../,,/24:06/,,
,\_    Submit paper...,,,24:06,
,\_      Finish methodology and approach for...,,,,11:58
,\_      Finish the analysis section,,,,3:15
,\_      Review paper one more time,,,,3:38
,\_      Editing,,,,4:15
,\_      Finish the second round of editing,,,,1:00
,\_  /MOOC for Reproducible Research/,,/7:14/,,
,\_    Module 1,,,3:09,
,\_    Module 2,,,4:05,
,*2 Areas*,*148:41*,,,
,\_  /Learn Languages/,,/67:17/,,
,\_  /Researching/,,/49:03/,,
,\_    Ask some questions,,,9:32,
,\_    Skype Meeting ,,,39:31,
,\_  /System Dynamics study/,,/32:21/,,
,\_    Meeting  ,,,32:21,
```

Thanks a bunch
Bala

**Comment by amoghpj** [comment]
Hi Bala,

Thanks for the feedback! 
At the outset, I have to mention that my python script is customized to my workflow, so you might have
to change lines 69-70 of the script to get it to work for you. Specifically, I want to generate reports from a diary.org file that is a datetree.
# Explanation of my workflow
My org capture refiles to a diary datetree which looks like this on a typical day:
```
*** 2018-11-06 Tuesday
**** DONE tuesday class                                               :class:
     CLOSED: [2018-11-06 Tue 11:39]
     :LOGBOOK:
     CLOCK: [2018-11-06 Tue 09:30]--[2018-11-06 Tue 11:39] =>  2:09
     :END:
   [2018-11-06 Tue]
**** DONE starting mineig=0.001 runs with new code.             :NutSig:work:
     CLOSED: [2018-11-06 Tue 15:28]
     :LOGBOOK:
     CLOCK: [2018-11-06 Tue 11:39]--[2018-11-06 Tue 15:28] =>  3:49
     :END:
   [2018-11-06 Tue]
**** DONE Meeting CSB                                               :MEETING:
     CLOSED: [2018-11-08 Thu 11:16]
     :LOGBOOK:
     CLOCK: [2018-11-06 Tue 15:28]--[2018-11-06 Tue 18:10] =>  2:42
     :END:
   <2018-11-06 Tue>
```
My `class.csv` (for my classes) looks something like this:
```
File,Headline,Time,,,
,ALL *Total time*,*12:39*,,,
diary.org,*File time*,*12:39*,,,
,2018,12:39,,,
,\_  2018-11 November,,12:39,,
,\_    2018-11-12 Monday,,,4:27,
,"\_      Reading chapter from textbook,...",,,,4:27
,\_    2018-11-13 Tuesday,,,6:33,
,\_      Tuesday class,,,,1:38
,\_      finishing homework,,,,4:55
,\_    2018-11-15 Thursday,,,1:39,
,\_      Thursday class,,,,1:39
```
As you can see, the top level heading here is a 'time stamp' from the org-capture. My python script looks for the `day_of_week` in the headline, which in my example is `Monday`,`Tuesday`, and `Thursday`. 
Really, the purpose of my script is to make a bar graph showing my tasks for *each day of the week*. Here is my capture template for clocking in to tasks:
```
(setq org-capture-templates
        '(
          ("c" "Clock tasks")
          ("cw" "work" entry (file+datetree "~/orgs/diary.org")
           "* IN-PROGRESS %? %^g:work:\n%u\n%a\n" :clock-in t :clock-resume t)
          ("cc" "class" entry (file+datetree "~/orgs/diary.org")
           "* IN-PROGRESS %? :class:\n%u\n%a\n" :clock-in t :clock-resume t)
          ("cm" "meeting" entry (file+datetree "~/orgs/diary.org")
           "* IN-PROGRESS Meeting %? :MEETING:\n%t" :clock-in t :clock-resume t)
))
```
# Cause of error
In your example, you seem to be clocking directly in your `todo.org` file, and my script doesn't return any numeric value because it doesn't find a day-of-the-week keyword.
 
# Resources
Since you have a very different workflow in terms of clocking tasks, I recommend the following link:
https://emacs.stackexchange.com/questions/23808/how-to-plot-summaries-of-timestamps-of-different-projects-clocking-in-and-out
This method generates a table of clocked times *per tag* and not *per day*. The org table generated by this script can then be plotted using any language. 
I have come across one other person who had made a much neater org-mode solution for plotting clocked hours. It might have been in relation to org-trello, but I can't find the link anymore.

# Potential Solution
I am glad someone tried my method, and I believe it is really an ugly hack that works for my needs, as I clock all tasks to a single datetree. I highly recommend using any other tool to parse and plot your csv file(s) as you see fit. Hope this explanation is useful. I might be able to help customize the python script for your needs if you can share the general structure of your tasks that you clock. Let me know if I can help in any other way!

Cheers,
Amogh

**Comment by balaramadurai** [comment]
Hi @amoghpj,
  Thank you so much for such a detailed reply. Ok, I got part of the answer already by staring at your code, but didn't know much of it. Anyways, yes, looks like I may have to get better at python or R or one of those things that I have been avoiding in org mode :smile: 

I will certainly look into the links you've sent and I will get started on some embedded stuff to get the pie-charts for my clocked times.

Thanks and have a great day!
Bala
